language: node_js
sudo :  required
node_js:
  - "6"
  - "6.1"
  - "5.11"
  - "4.5"
  - "4.4"
before_install:
 - export CHROME_BIN=/usr/bin/google-chrome
 - export DISPLAY=:99.0
 - sh -e /etc/init.d/xvfb start
 - sudo apt-get update
 - sudo apt-get install -y libappindicator1 fonts-liberation
 - wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
 - sudo dpkg -i google-chrome*.deb

after_script: cat ./coverage/**/lcov.info | ./node_modules/.bin/coveralls
#  - npm install -g gulp